parameters:
  gesdinet.jwtrefreshtoken.user_refresh_token.class: Gesdinet\JWTRefreshTokenBundle\Entity\UserRefreshToken

services:
    gesdinet_jwtrefreshtokenbundle.eventlistener.refreshtokenlistener:
        class: Gesdinet\JWTRefreshTokenBundle\EventListener\RefreshTokenListener
        arguments: [ @gesdinet.jwtrefreshtoken.user_refresh_token_manager, %gesdinet_jwt_refresh_token.ttl% ]
        tags:
            - { name: kernel.event_subscriber }

    gesdinet.jwtrefreshtoken.send_token:
        class: Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener
        arguments: [ @gesdinet.jwtrefreshtoken.user_refresh_token_manager ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: attachRefreshToken }

    gesdinet.jwtrefreshtoken.user_refresh_token_manager:
        class: Gesdinet\JWTRefreshTokenBundle\Doctrine\UserRefreshTokenManager
        arguments: [@fos_user.entity_manager, %gesdinet.jwtrefreshtoken.user_refresh_token.class%]
